DROP TABLE "tags";
CREATE TABLE tags (
	id INTEGER NOT NULL, 
	normalized_tag VARCHAR NOT NULL, 
	priority INTEGER, 
	is_active BOOLEAN, synonyms VARCHAR, german_normalized_tag VARCHAR NOT NULL, 
	PRIMARY KEY (id)
);

INSERT INTO "tags" ("id", "normalized_tag", "priority", "is_active", "synonyms", "german_normalized_tag") VALUES
(1, 'Co-op', 50, '1', 'Cooperative,Co-op,Kooperativ,Koop, Co-Op', 'Kooperativ'),
(2, 'Strategy', 1, '1', 'Strategie,Strategy,Strat', 'Strategie'),
(3, 'Area-Control', 1, '1', 'Area Control,Area-Control,Area Influence,Area-Majority,AreaControl,Area_Majority', 'Area-Control'),
(4, 'Competitive', 1, '1', 'Competitive,Kompetetiv,Wettbewerb', 'Competitive'),
(5, 'Assymetric', 1, '1', 'Assymetric,Assymetrisch,Asymmetrisch,Variable-Player-Powers', 'Asymmetrisch'),
(6, 'Miniatures', 1, '1', 'Miniatures,Miniaturen,Figures,Figuren', 'Miniatures'),
(7, 'Mythology', 1, '1', 'Mythology,Mythologie,Mythen', 'Mythologie'),
(8, 'Player-Elimination', 1, '1', 'Player Elimination,Player-Elimination,Spieler-Eliminierung,Spieler-Elimination', 'Player-Elimination'),
(9, 'Egypt', 1, '1', 'Egypt,Ägypten,Ägyptisch', 'Egypt'),
(10, 'Tile-placement', 1, '1', 'Tile Placement,Tile-Placement,Plättchenlegen,Plättchen-Legen,Plättchenlegespiel', 'Tile-placement'),
(11, 'Set-collection', 1, '1', 'Set Collection,Set-Collection,Kartensammlung,Karten-Sammlung', 'Set-collection'),
(12, 'Open-drafting', 1, '1', 'Open Drafting,Open-Drafting,Offenes Drafting,Offenes-Drafting', 'Open-drafting'),
(13, 'Family-game', 1, '1', 'Familienspiel,Familienspiele,Family Game,Family,Familie,Kinderspiel,Kids,Kinderspiel', 'Familienspiel'),
(14, 'Game-of-the-year', 1, '1', 'Spiel des Jahres,SdJ,Spiel-Des-Jahres,Spiel-des-Jahres,spiel_des_jahres', 'Spiel des Jahres'),
(15, 'Card-Drafting', 1, '1', 'Card Drafting,Card-Drafting,Kartendrafting,Karten-Drafting,Card_Drafting', 'Card-Drafting'),
(16, 'Eurogame', 1, '1', 'Eurogame,Euro-Game,Euro,Euro-Style', 'Eurogame'),
(17, 'Tableau-Builder', 1, '1', 'Tableau Builder,Tableau-Builder,Tableau-Building,Tableau-Building', 'Tableau-Builder'),
(18, 'Card-Game', 1, '1', 'Card Game,Card-Game,Kartenspiel,Karten-Spiel,card,cards,cardgame', 'Kartenspiel'),
(19, 'Viking', 1, '1', 'Viking,Vikings,Wikinger', 'Wikinger'),
(20, 'Fantasy', 1, '1', 'Fantasy,Fantasie,Phantasy', 'Fantasy'),
(21, 'Kennerspiel', 1, '1', 'Kennerspiel,Kennerspiel des Jahres,Kennerspiel-des-Jahres,Kennerspiel-des-Jahres,Kenner&Expertenspiele', 'Kennerspiel'),
(22, 'Expert-game', 1, '1', 'Expertenspiel,Expertenspiel des Jahres,Expertenspiel-des-Jahres,Expertenspiel-des-Jahres,Kenner&Expertenspiele,Expert', 'Expertenspiel'),
(23, 'Ameritrash', 1, '1', 'Ameritrash,Amerikatrash,Amerika-Trash', 'Ameritrash'),
(24, 'Worker-Placement', 1, '1', 'Worker Placement,Worker-Placement,Arbeiterplatzierung,Arbeiter-Platzierung', 'Worker-Placement'),
(25, 'Deckbuilding', 1, '1', 'Deck Builder,Deck-Builder,Deckbuilding,Deck-Building', 'Deckbuilder'),
(26, 'Roll-And-Write', 1, '1', 'Roll and Write,Roll-And-Write,Roll-n-Write,Roll-n-Write,roll-&-write,X-And-Write', 'Roll-And-Write'),
(27, 'Flip-and-write', 1, '1', 'Flip and Write,Flip-and-Write,Flip-n-Write,Flip-n-Write,flip-&-write', 'Flip-and-write'),
(28, 'Sci-Fi', 1, '1', 'Sci-Fi,Science Fiction,Science-Fiction,ScienceFiction', 'Sci-Fi'),
(29, 'Duel', 30, '1', 'Duell,Duel,Duellspiel,Duel Game, 2-Player, 2-Players', 'Duell'),
(30, 'Modular-Board', 1, '1', 'Modular Board,Modular-Board,Modulares Spielbrett,Modulares-Spielbrett', 'Modulares Spielbrett'),
(31, 'Zombies', 1, '1', 'Zombies,Zombie,Zombi', 'Zombies'),
(32, 'Push-Your-Luck', 1, '1', 'Push Your Luck,Push-Your-Luck,Push-Your-Luck-Spiel,Push-Your-Luck-Game', 'Push-Your-Luck'),
(33, 'Deduction', 5, '1', 'Deduction,Deduktions-Spiel,Deduktions-Spiel,Déduction,Deduktion', 'Deduktion'),
(34, 'EngineBuilding', 1, '1', 'Engine Building,Engine-Building,Enginebuilder,Engine-Builder', 'Enginebuilder'),
(35, 'Cthulhu', 1, '1', 'Cthulhu,Cthulhu-Mythos,Cthulhu-Mythologie', 'Cthulhu'),
(36, 'Robots', 1, '1', 'Robots,Robot,Roboter', 'Roboter'),
(37, 'Chaotic', 1, '1', 'chaotic,chaotisch,chaos', 'Chaotisch'),
(38, 'Geschicklichkeit', 1, '1', 'Geschicklichkeit,Geschicklichkeitsspiel,Skill,Skill Game,Geschicklichkeit', 'Geschicklichkeit'),
(39, 'Dice-game', 1, '1', 'Würfelspiel,Würfel,Würfel-Spiel,Dice Game,Dice,Component:Dice ', 'Würfelspiel'),
(40, 'Party-Game', 1, '1', 'Party Game,Party-Game,Partyspiel,Party,Party-Spiel', 'Partyspiel'),
(41, 'Animals', 1, '1', 'Animals,Animal,Tiere,Tier', 'Tiere'),
(42, 'Quiz', 1, '1', 'Quiz,Quiz-Spiel,Quiz Game,Quizspiel', 'Quiz'),
(43, 'Halloween', 1, '1', 'Halloween,Halloween-Spiel,Halloween-Game', 'Halloween'),
(44, 'Word-Game', 7, '1', 'word-game, Wordgame, Wortspiel, wortspiel, word, Word-games', 'Wortspiel');