"""Add autoincrement to games

Revision ID: 46e34e225545
Revises: b8f3624a504f
Create Date: 2025-02-11 11:35:14.278273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46e34e225545'
down_revision: Union[str, None] = 'b8f3624a504f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_games_bgg_id', table_name='games')
    op.create_index(op.f('ix_games_bgg_id'), 'games', ['bgg_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_bgg_id'), table_name='games')
    op.create_index('ix_games_bgg_id', 'games', ['bgg_id'], unique=False)
    # ### end Alembic commands ###
