"""Change ean from Integer to String

Revision ID: 59a7838320a5
Revises: 46e34e225545
Create Date: 2025-02-14 09:48:09.983776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a7838320a5'
down_revision: Union[str, None] = '46e34e225545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'ean',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index('games_ean_key', table_name='games')
    op.create_unique_constraint(None, 'games', ['ean'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='unique')
    op.create_index('games_ean_key', 'games', ['ean'], unique=True)
    op.alter_column('games', 'ean',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
