"""Ensure ON DELETE CASCADE is set

Revision ID: 830e9e63e6a5
Revises: 870cbb0df089
Create Date: 2025-03-11 08:04:27.869366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '830e9e63e6a5'
down_revision: Union[str, None] = '870cbb0df089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
