"""Ensure ON DELETE CASCADE is set

Revision ID: 870cbb0df089
Revises: f63e1aeb6b7d
Create Date: 2025-03-11 07:59:53.307577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870cbb0df089'
down_revision: Union[str, None] = 'f63e1aeb6b7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
