"""Add cascade delete to game relationships

Revision ID: 029707e1a360
Revises: 871e4196dded
Create Date: 2025-03-11 07:55:16.010763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '029707e1a360'
down_revision: Union[str, None] = '871e4196dded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_game_knowledge_user_id_fkey', 'user_game_knowledge', type_='foreignkey')
    op.create_foreign_key(None, 'user_game_knowledge', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_game_knowledge', type_='foreignkey')
    op.create_foreign_key('user_game_knowledge_user_id_fkey', 'user_game_knowledge', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
