"""Add many-to-many relationship between Game and Tag

Revision ID: 03b487849f90
Revises: 5255bc099374
Create Date: 2025-01-18 11:03:39.837667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03b487849f90'
down_revision: Union[str, None] = '5255bc099374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('tags', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
