"""Add player_age to Game model

Revision ID: 41cb4214aa98
Revises: b05cca3eb062
Create Date: 2025-01-14 09:17:36.019133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41cb4214aa98'
down_revision: Union[str, None] = 'b05cca3eb062'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('player_age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'player_age')
    # ### end Alembic commands ###
