"""Add tags table

Revision ID: 5255bc099374
Revises: 8887db815200
Create Date: 2025-01-18 10:10:25.478446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5255bc099374'
down_revision: Union[str, None] = '8887db815200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('german_normalized_tag', sa.String(), nullable=False))
    op.drop_index('ix_tags_germand_normalized_tag', table_name='tags')
    op.create_index(op.f('ix_tags_german_normalized_tag'), 'tags', ['german_normalized_tag'], unique=True)
    op.drop_column('tags', 'german_synonyms')
    op.drop_column('tags', 'germand_normalized_tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('germand_normalized_tag', sa.VARCHAR(), nullable=False))
    op.add_column('tags', sa.Column('german_synonyms', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_tags_german_normalized_tag'), table_name='tags')
    op.create_index('ix_tags_germand_normalized_tag', 'tags', ['germand_normalized_tag'], unique=1)
    op.drop_column('tags', 'german_normalized_tag')
    # ### end Alembic commands ###
