"""Fix backref names for GameSimilarity

Revision ID: 8825f191ba39
Revises: b4ac6af95557
Create Date: 2025-01-18 13:23:18.594799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8825f191ba39'
down_revision: Union[str, None] = 'b4ac6af95557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
