"""Remove old similar_games column

Revision ID: b4ac6af95557
Revises: 03b487849f90
Create Date: 2025-01-18 13:15:59.559440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ac6af95557'
down_revision: Union[str, None] = '03b487849f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_similarities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('similar_game_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('shared_tags_count', sa.Integer(), nullable=False),
    sa.Column('tag_priority_sum', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['similar_game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_similarities_game_id'), 'game_similarities', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_similarities_id'), 'game_similarities', ['id'], unique=False)
    op.create_index(op.f('ix_game_similarities_similar_game_id'), 'game_similarities', ['similar_game_id'], unique=False)
    op.drop_column('games', 'similar_games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('similar_games', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_game_similarities_similar_game_id'), table_name='game_similarities')
    op.drop_index(op.f('ix_game_similarities_id'), table_name='game_similarities')
    op.drop_index(op.f('ix_game_similarities_game_id'), table_name='game_similarities')
    op.drop_table('game_similarities')
    # ### end Alembic commands ###
