"""Add complexity_label to games

Revision ID: b8f3624a504f
Revises: 29b41b64989a
Create Date: 2025-02-11 10:56:00.348030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f3624a504f'
down_revision: Union[str, None] = '29b41b64989a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('complexity_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'complexity_label')
    # ### end Alembic commands ###
