"""Add tags table

Revision ID: c525a71a47a0
Revises: cd6f3ba64367
Create Date: 2025-01-18 10:05:02.408917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c525a71a47a0'
down_revision: Union[str, None] = 'cd6f3ba64367'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('germand_normalized_tag', sa.String(), nullable=False))
    op.add_column('tags', sa.Column('synonyms', sa.String(), nullable=True))
    op.create_index(op.f('ix_tags_germand_normalized_tag'), 'tags', ['germand_normalized_tag'], unique=True)
    op.drop_column('tags', 'english_synonyms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('english_synonyms', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_tags_germand_normalized_tag'), table_name='tags')
    op.drop_column('tags', 'synonyms')
    op.drop_column('tags', 'germand_normalized_tag')
    # ### end Alembic commands ###
