"""Fix delete-orphan issue in GameSimilarity

Revision ID: f63e1aeb6b7d
Revises: 029707e1a360
Create Date: 2025-03-11 07:57:15.930446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f63e1aeb6b7d'
down_revision: Union[str, None] = '029707e1a360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
